name: Sync with Upstream AzerothCore

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6:00 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/azerothcore/azerothcore-wotlk.git || true
          git remote set-url upstream https://github.com/azerothcore/azerothcore-wotlk.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream

      - name: Check for updates
        id: check_updates
        run: |
          # Compare our master with upstream/master
          LOCAL=$(git rev-parse master)
          REMOTE=$(git rev-parse upstream/master)
          
          if [ "$LOCAL" != "$REMOTE" ]; then
            echo "updates_available=true" >> $GITHUB_OUTPUT
            echo "Updates available from upstream"
          else
            echo "updates_available=false" >> $GITHUB_OUTPUT
            echo "No updates available"
          fi

      - name: Merge upstream changes
        if: steps.check_updates.outputs.updates_available == 'true'
        run: |
          git checkout master
          git merge upstream/master --no-edit --allow-unrelated-histories || {
            echo "Merge conflict detected. Creating a pull request instead."
            git merge --abort
            exit 1
          }

      - name: Push changes
        if: steps.check_updates.outputs.updates_available == 'true'
        run: |
          git push origin master

      - name: Create PR on merge conflict
        if: failure() && steps.check_updates.outputs.updates_available == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-upstream-${{ github.run_number }}
          title: "Sync with upstream AzerothCore - Manual merge required"
          body: |
            This PR contains updates from the upstream AzerothCore repository that require manual resolution due to merge conflicts.
            
            **Upstream repository**: https://github.com/azerothcore/azerothcore-wotlk
            
            Please review the changes and resolve any conflicts manually.
            
            Auto-generated by GitHub Actions.
          base: master